# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161011_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='next_qid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_branch', to='app.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='next_qid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Question'),
        ),
    ]
