# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161011_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyid', models.TextField()),
                ('qid', models.TextField()),
                ('user', models.TextField()),
                ('res', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_name', models.TextField()),
                ('first_qid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Question')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set([('surveyid', 'user')]),
        ),
        migrations.AddField(
            model_name='question',
            name='survey_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Survey'),
            preserve_default=False,
        ),
    ]
